-- https://school.programmers.co.kr/learn/courses/30/lessons/131117
-- 소요 시간 : 13분 19초
SELECT 
o.PRODUCT_ID, p.PRODUCT_NAME, SUM(o.AMOUNT) * PRICE AS `TOTAL_SALES` 
FROM FOOD_ORDER o
INNER JOIN FOOD_PRODUCT p ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE YEAR(o.PRODUCE_DATE) = 2022 AND MONTH(o.PRODUCE_DATE) = 5
GROUP BY o.PRODUCT_ID
ORDER BY `TOTAL_SALES` DESC, o.PRODUCT_ID ASC;