-- https://school.programmers.co.kr/learn/courses/30/lessons/276035
-- 소요 시간 : 9분 53초
SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME FROM DEVELOPERS D
WHERE D.SKILL_CODE & (SELECT SUM(S.CODE) FROM SKILLCODES S WHERE S.CATEGORY LIKE "Front End") > 0
ORDER BY D.ID ASC;

-- WITH와 JOIN 사용
WITH FE AS (
    SELECT *
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT DISTINCT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS A
INNER JOIN FE B ON A.SKILL_CODE & B.CODE
ORDER BY A.ID;

-- SELECT DISTINCT : 중복되는 데이터는 제거