-- https://school.programmers.co.kr/learn/courses/30/lessons/131537
-- 소요 시간 : 10분
WITH TABLES1 AS (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE_SALE
    UNION
    SELECT SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT FROM OFFLINE_SALE
    -- UNION 시 컬럼 수가 다를 경우 위와 같이 NULL을 추가
)

SELECT 
date_format(SALES_DATE, '%Y-%m-%d') AS `SALES_DATE`, PRODUCT_ID, USER_ID, SALES_AMOUNT 
FROM TABLES1
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
ORDER BY `SALES_DATE`, PRODUCT_ID, USER_ID;